// Auto-generated by tools/update_stage.py — do not edit by hand.
// Regenerated daily. If this file is missing or stale, index.html falls
// back to computing tonight's stage in the browser from the embedded schedule.
window.STAGE_TODAY = {
  "generated_at": "2026-07-15T18:14:09.487454+12:00",
  "nz_date": "2026-07-15",
  "as_of_date": "2026-07-15",
  "boundary_hour": 10,
  "status": "racing",
  "watched": {
    "num": 10,
    "date": "2026-07-14"
  },
  "preview": {
    "num": 11,
    "date": "2026-07-15",
    "start": "Vichy",
    "finish": "Nevers",
    "distance_km": 161.3,
    "type": "Flat",
    "note": "Flat transition through central France; sprinters back in play.",
    "headline": "Sprinters resurface in Nevers",
    "watch_for": "A flat transition through central France brings the fast men back into play, with the sprint teams keen to control a straightforward run to Nevers. The question is whether a stubborn break can spoil the party on a day everyone expects to end in a bunch kick. Watch the peloton's willingness to chase.",
    "riders_to_watch": [
      "Tim Merlier",
      "Jasper Philipsen",
      "Arnaud De Lie",
      "Fernando Gaviria",
      "Pavel Bittner",
      "Milan Fretin"
    ],
    "nz_note": "Comfortably a last-3km watch.",
    "climb_m": 1107,
    "summit_finish": false
  },
  "abandoned": []
};
