// Auto-generated by tools/update_stage.py — do not edit by hand.
// Regenerated daily. If this file is missing or stale, index.html falls
// back to computing tonight's stage in the browser from the embedded schedule.
window.STAGE_TODAY = {
  "generated_at": "2026-07-08T10:00:01.860193+12:00",
  "nz_date": "2026-07-08",
  "as_of_date": "2026-07-08",
  "boundary_hour": 10,
  "status": "racing",
  "watched": {
    "num": 4,
    "date": "2026-07-07"
  },
  "preview": {
    "num": 5,
    "date": "2026-07-08",
    "start": "Lannemezan",
    "finish": "Pau",
    "distance_km": 158.3,
    "type": "Flat",
    "note": "Transitional day into Pau; a likely bunch sprint after the opening mountains.",
    "headline": "The fast men get their turn in Pau",
    "watch_for": "A transitional day off the back of the mountains, running into Pau where the sprint trains will want to reassemble the bunch and set up a bunch gallop. The intrigue is whether the sprinters' teams have the legs to reel in a hopeful break after two hard days. Watch the lead-out choreography in the final kilometres.",
    "riders_to_watch": [
      "Tim Merlier",
      "Jasper Philipsen",
      "Biniam Girmay",
      "Arnaud De Lie",
      "Fernando Gaviria",
      "Milan Fretin"
    ],
    "nz_note": "A classic skip-to-the-last-3km stage if you're short on evening time.",
    "climb_m": 1395,
    "summit_finish": false
  },
  "abandoned": []
};
