#!/usr/bin/env python3
"""
Daily updater for the Tour de France 2026 home page.

Works out, for the current New Zealand date, which stage's highlights to watch
*tonight* (NZ evening) and which stage is racing *overnight* tonight, then writes
`stage-today.js` next to index.html.

Timing model (confirmed): NZ is +10h ahead of France (CEST) during the Tour.
A stage raced on European date D finishes in NZ's small hours of D+1, so its
highlights are watched on the NZ evening of D+1.

    tonight's highlights  = stage whose European date == (NZ today - 1 day)
    racing overnight      = stage whose European date ==  NZ today

The stage selection is deterministic. When the race is on, an optional `claude -p`
step then adds spoiler-safe context (a tactical preview, the standings entering
tonight's stage, and the DNF list) — see the AI-enrichment section below. Pass
`--no-ai` for the deterministic-only path.

Python 3.9 compatible. No `X | Y` unions.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA_PATH = os.path.join(ROOT, "tdf_data.json")
OUT_PATH = os.path.join(ROOT, "stage-today.js")

NZ = ZoneInfo("Pacific/Auckland")


def load_data() -> Dict[str, Any]:
    with open(DATA_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


def find_stage_by_date(stages, iso_date: str) -> Optional[Dict[str, Any]]:
    for s in stages:
        if s.get("date") == iso_date:
            return s
    return None


def build_payload(data: Dict[str, Any], now_nz: datetime) -> Dict[str, Any]:
    stages = data.get("stages", [])
    nz_today = now_nz.date()
    tonight_date = (nz_today - timedelta(days=1)).isoformat()  # European stage date
    overnight_date = nz_today.isoformat()

    tonight = find_stage_by_date(stages, tonight_date)
    overnight = find_stage_by_date(stages, overnight_date)

    # Race status messaging
    dated = [s for s in stages if s.get("date")]
    first_date = min((s["date"] for s in dated), default=None)
    last_date = max((s["date"] for s in dated), default=None)

    if first_date and tonight_date < first_date and tonight is None:
        status = "pre-race"
    elif last_date and tonight_date > last_date:
        status = "finished"
    elif tonight is None and overnight is None:
        status = "rest-day"
    else:
        status = "racing"

    return {
        "generated_at": now_nz.isoformat(),
        "nz_date": nz_today.isoformat(),
        "tonight_watch_date": tonight_date,
        "overnight_race_date": overnight_date,
        "status": status,
        "tonight": tonight,     # the stage to watch highlights of tonight (NZ evening)
        "overnight": overnight,  # the stage racing overnight tonight (NZ)
    }


def write_js(payload: Dict[str, Any]) -> None:
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    js = (
        "// Auto-generated by tools/update_stage.py — do not edit by hand.\n"
        "// Regenerated daily. If this file is missing or stale, index.html falls\n"
        "// back to computing tonight's stage in the browser from the embedded schedule.\n"
        "window.STAGE_TODAY = " + body + ";\n"
    )
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(js)


# ----------------------------------------------------------------------------
# AI enrichment — spoiler-safe daily research via `claude -p`
#
# THE SPOILER BOUNDARY (critical): tonight we watch highlights of stage K. We
# have already watched everything up to and including stage K-1. So the job may
# ONLY use information current as of the START of stage K (= end of stage K-1):
#   - standings AFTER stage K-1  (= the numbers riders START stage K with)
#   - abandonments THROUGH stage K-1 only
#   - a tactical PREVIEW of stage K written from that pre-stage picture — never
#     its result. The model is told not to look up stage K at all.
# ----------------------------------------------------------------------------

def find_claude() -> Optional[str]:
    cand = shutil.which("claude")
    if cand:
        return cand
    for p in ("~/.claude/local/claude", "~/.local/bin/claude",
              "/opt/homebrew/bin/claude", "/usr/local/bin/claude"):
        p = os.path.expanduser(p)
        if os.path.exists(p):
            return p
    return None


def roster_block(data: Dict[str, Any]) -> str:
    lines = []  # type: List[str]
    for t in data.get("teams", []):
        leader = t.get("road_leader") or ""
        names = []
        for r in t.get("riders", []):
            tag = " [LEADER]" if leader and r.get("name") and r["name"] in leader else ""
            names.append("%s (%s)%s" % (r.get("name", "?"), r.get("specialty", "?"), tag))
        lines.append("%s — %s" % (t.get("team_name", "?"), "; ".join(names)))
    return "\n".join(lines)


def build_prompt(data: Dict[str, Any], payload: Dict[str, Any]) -> str:
    t = payload["tonight"]
    K = t.get("num")
    prev = (K - 1) if isinstance(K, int) and K > 1 else 0
    race = data.get("race", {})
    profile = "%s, %s km, ~%s m climbing%s" % (
        t.get("type", "?"), t.get("distance_km", "?"), t.get("climb_m", "?"),
        ", SUMMIT FINISH" if t.get("summit_finish") else "")
    standings_ask = (
        "There are no standings yet (stage 1 has not been completed) — return empty arrays."
        if prev == 0 else
        ("Fetch these four classifications AFTER STAGE %d ONLY (the numbers riders start tonight's "
         "Stage %d with), EACH as a top-10 table: (1) General Classification with time gaps; "
         "(2) Points / Green jersey with points totals; (3) Mountains / Polka-dot (KOM) with points "
         "totals; (4) Young rider / White jersey with time gaps." % (prev, K)))
    return (
        "You are the spoiler-safe race desk for a couple in New Zealand who watch Tour de France "
        "highlights in their evening. Tonight they will watch the highlights of STAGE %d of the 2026 "
        "Tour de France. They have ALREADY watched every stage up to and including stage %d.\n\n"
        "ABSOLUTE SPOILER RULE — break this and you ruin their night:\n"
        "  * You may ONLY use information current as of the START of stage %d (i.e. the end of stage %d).\n"
        "  * NEVER look up, infer, or reveal the result of stage %d (tonight's highlights) or anything after it.\n"
        "  * Do NOT search for 'stage %d result/winner'. If a search result shows tonight's or a later "
        "stage's outcome, IGNORE it completely.\n"
        "  * Standings must be AFTER STAGE %d. Abandonments must be THROUGH STAGE %d only.\n\n"
        "TONIGHT'S STAGE %d: %s -> %s. Profile: %s.\n"
        "Race context: %s. %s\n\n"
        "%s\n\n"
        "Also compile the list of riders who have ABANDONED / been eliminated / did-not-start THROUGH "
        "stage %d (use web search: 'Tour de France 2026 abandons / non-starters'). Use rider names spelled "
        "EXACTLY as they appear in this startlist so they can be matched:\n%s\n\n"
        "Now write a rich, SPOILER-FREE 'what to watch for' preview of tonight's Stage %d (4-6 sentences). "
        "Make it tactically specific and rider-aware, grounded in the standings above and each rider's real "
        "characteristics and race situation — e.g. a GC contender who is down on time and must attack; a "
        "renowned descender who will chance a move on a technical descent; a sprinter's team needing to "
        "control a flat day; a summit finish suiting the pure climbers. Name specific riders and WHY the "
        "stage profile plus their position makes them act. Do not state or hint at any result.\n\n"
        "Return ONLY a single JSON object, no prose, of exactly this shape:\n"
        "{\"watch_for\":\"...\",\"riders_to_watch\":[\"Name\",...],"
        "\"standings\":{\"as_of_label\":\"entering Stage %d (after Stage %d)\","
        "\"gc\":[{\"rank\":1,\"rider\":\"...\",\"team\":\"...\",\"gap\":\"race lead\"}],"
        "\"points\":[{\"rank\":1,\"rider\":\"...\",\"team\":\"...\",\"pts\":123}],"
        "\"kom\":[{\"rank\":1,\"rider\":\"...\",\"team\":\"...\",\"pts\":45}],"
        "\"youth\":[{\"rank\":1,\"rider\":\"...\",\"team\":\"...\",\"gap\":\"race lead\"}]},"
        "\"abandoned\":[{\"name\":\"Exact Name\",\"stage\":<int>,\"reason\":\"...\"}],"
        "\"confidence\":\"high|medium|low\",\"sources\":[\"url\"]}"
        % (K, prev, K, prev, K, K, prev, prev, K, t.get("start", "?"), t.get("finish", "?"),
           profile, race.get("overview", ""), standings_ask, standings_ask, prev,
           roster_block(data), K, K, prev))


def extract_json(text: str) -> Optional[Dict[str, Any]]:
    # try whole thing, then the last balanced object
    try:
        return json.loads(text)
    except Exception:
        pass
    depth = 0
    start = -1
    best = None
    for i, ch in enumerate(text):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start >= 0:
                chunk = text[start:i + 1]
                try:
                    best = json.loads(chunk)
                except Exception:
                    pass
    return best


def run_ai(data: Dict[str, Any], payload: Dict[str, Any], timeout: int) -> Optional[Dict[str, Any]]:
    claude = find_claude()
    if not claude:
        print("[update_stage] claude binary not found — skipping AI enrichment", file=sys.stderr)
        return None
    prompt = build_prompt(data, payload)
    cmd = [claude, "-p", prompt, "--output-format", "json", "--allowedTools", "WebSearch"]
    try:
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=ROOT)
    except subprocess.TimeoutExpired:
        print("[update_stage] AI enrichment timed out after %ss — using base payload" % timeout, file=sys.stderr)
        return None
    except Exception as e:  # noqa
        print("[update_stage] AI enrichment error: %s" % e, file=sys.stderr)
        return None
    out = res.stdout or ""
    wrapper = None
    try:
        wrapper = json.loads(out)
    except Exception:
        wrapper = None
    text = wrapper.get("result", out) if isinstance(wrapper, dict) else out
    ai = extract_json(text)
    if not ai:
        print("[update_stage] could not parse AI JSON — using base payload", file=sys.stderr)
        return None
    return ai


def merge_ai(payload: Dict[str, Any], ai: Dict[str, Any]) -> None:
    t = payload.get("tonight")
    if t:
        if ai.get("watch_for"):
            t["watch_for"] = ai["watch_for"]
            t["contextual"] = True
        if ai.get("riders_to_watch"):
            t["riders_to_watch"] = ai["riders_to_watch"]
    st = ai.get("standings")
    if isinstance(st, dict) and st.get("gc"):
        payload["standings"] = st
    ab = ai.get("abandoned")
    if isinstance(ab, list):
        # SPOILER SAFETY NET: never surface a DNF from tonight's stage or later —
        # that would betray something about the highlights not yet watched.
        K = (t or {}).get("num")
        if isinstance(K, int):
            ab = [a for a in ab if not (isinstance(a.get("stage"), int) and a["stage"] >= K)]
        payload["abandoned"] = ab
    payload["ai"] = {"confidence": ai.get("confidence"), "sources": ai.get("sources", [])}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-ai", action="store_true", help="skip claude enrichment (deterministic only)")
    ap.add_argument("--timeout", type=int, default=300, help="claude -p timeout seconds")
    a = ap.parse_args()

    now_nz = datetime.now(NZ)
    data = load_data()
    payload = build_payload(data, now_nz)

    if not a.no_ai and payload.get("status") == "racing" and payload.get("tonight"):
        ai = run_ai(data, payload, a.timeout)
        if ai:
            merge_ai(payload, ai)
            print("[update_stage] AI enrichment merged (%d GC rows, %d abandoned)" % (
                len((payload.get("standings") or {}).get("gc", [])),
                len(payload.get("abandoned", []))))

    write_js(payload)
    t = payload.get("tonight")
    label = ("Stage %s (%s)" % (t["num"], t.get("type", "")) if t else "nothing yet")
    print("[update_stage] NZ %s -> tonight's highlights: %s [status=%s]" % (
        payload["nz_date"], label, payload["status"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
